import asyncio

import pytest
from fastapi import HTTPException

from backend.app.models import GeneratedIssue, ScanIssue
from backend.app.services import github


class FakeResponse:
    def __init__(self, status_code=200, payload=None, headers=None):
        self.status_code = status_code
        self._payload = payload or {}
        self.headers = headers or {}

    def json(self):
        return self._payload


class FakeClient:
    def __init__(self, response):
        self.response = response
        self.requests = []

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False

    async def get(self, url, params=None, headers=None):
        self.requests.append(("GET", url, params, headers))
        return self.response

    async def post(self, url, json=None, headers=None):
        self.requests.append(("POST", url, json, headers))
        return self.response

    async def put(self, url, json=None, headers=None):
        self.requests.append(("PUT", url, json, headers))
        return self.response


def scan_issue() -> ScanIssue:
    return ScanIssue(
        id="button-name",
        title="Buttons must have discernible text",
        severity="High",
        wcag_criterion="4.1.2",
        wcag_url="https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html",
        element="<button></button>",
        selector="header button.search-icon",
        impact="Screen reader users cannot identify the search button.",
        description="The button has no accessible name.",
        occurrences=1,
        tags=["accessibility", "wcag-4.1.2", "buttons", "aria"],
    )


def generated_issue() -> GeneratedIssue:
    return GeneratedIssue(
        title="[A11y] Search button has no accessible name",
        description="The search button is missing an accessible name.",
        repro_steps=["Open the page.", "Focus the search button."],
        expected_result="The button is announced as Search.",
        actual_result="The button is announced without a name.",
        severity="High",
        labels=["accessibility", "bug"],
        acceptance_criteria=["The button has an accessible name.", "The axe rule passes."],
        environment="Chrome and NVDA",
        wcag_reference="https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html",
    )


def patch_client(monkeypatch, response):
    fake = FakeClient(response)
    monkeypatch.setattr(github.httpx, "AsyncClient", lambda timeout: fake)
    return fake


def test_search_issues_normalizes_and_scores_results(monkeypatch):
    patch_client(
        monkeypatch,
        FakeResponse(
            payload={
                "items": [
                    {
                        "number": 7,
                        "title": "Search button accessibility name missing",
                        "state": "open",
                        "labels": [{"name": "accessibility"}],
                        "assignee": {"login": "hardik"},
                        "created_at": "2026-06-01T12:00:00Z",
                        "body": "WCAG 4.1.2 button-name failure in header.",
                        "html_url": "https://github.com/owner/repo/issues/7",
                    }
                ]
            }
        ),
    )
    results, summary, source = asyncio.run(github.search_issues(scan_issue(), "owner/repo"))
    assert source == "github"
    assert "ranked by" in summary
    assert results[0].number == 7
    assert results[0].similarity_score > 5
    assert "WCAG" in results[0].similarity_explanation


def test_search_issues_translates_rate_limit_to_fallback(monkeypatch):
    patch_client(
        monkeypatch,
        FakeResponse(
            status_code=403,
            payload={"message": "API rate limit exceeded"},
            headers={"x-ratelimit-remaining": "0", "x-ratelimit-reset": "1800000000"},
        ),
    )
    results, summary, source = asyncio.run(github.search_issues(scan_issue(), "owner/repo"))
    assert results
    assert source == "fallback"
    assert "rate limit exceeded" in summary.lower()


def test_markdown_body_contains_required_sections():
    body = github.markdown_body(generated_issue())
    assert "## Description" in body
    assert "## Steps to reproduce" in body
    assert "- [ ] The button has an accessible name." in body
    assert "Generated by A11y GitHub Issue Logger" in body


def test_create_issue_requires_github_token(monkeypatch):
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)
    with pytest.raises(HTTPException) as exc:
        asyncio.run(github.create_issue("owner/repo", generated_issue()))
    assert exc.value.status_code == 503


def test_create_issue_translates_github_error(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "token")
    patch_client(monkeypatch, FakeResponse(status_code=404, payload={"message": "Not Found"}))
    with pytest.raises(HTTPException) as exc:
        asyncio.run(github.create_issue("owner/repo", generated_issue()))
    assert exc.value.status_code == 404
    assert "repository was not found" in exc.value.detail


def test_create_issue_accepts_per_request_token_without_server_token(monkeypatch):
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)
    fake = patch_client(
        monkeypatch,
        FakeResponse(status_code=201, payload={"number": 99, "html_url": "https://github.com/owner/repo/issues/99"}),
    )
    result = asyncio.run(
        github.create_issue("owner/repo", generated_issue(), token="github_pat_userprovided")
    )
    assert result["number"] == 99
    # The per-request token must be the one sent to GitHub.
    _, _, _, headers = fake.requests[-1]
    assert headers["Authorization"] == "Bearer github_pat_userprovided"


def test_create_issue_prefers_request_token_over_server_token(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "server-token")
    fake = patch_client(
        monkeypatch,
        FakeResponse(status_code=201, payload={"number": 1, "html_url": "https://github.com/owner/repo/issues/1"}),
    )
    asyncio.run(github.create_issue("owner/repo", generated_issue(), token="ghp_requesttoken"))
    _, _, _, headers = fake.requests[-1]
    assert headers["Authorization"] == "Bearer ghp_requesttoken"


def test_create_issue_falls_back_to_server_token(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "server-token")
    fake = patch_client(
        monkeypatch,
        FakeResponse(status_code=201, payload={"number": 2, "html_url": "https://github.com/owner/repo/issues/2"}),
    )
    asyncio.run(github.create_issue("owner/repo", generated_issue()))
    _, _, _, headers = fake.requests[-1]
    assert headers["Authorization"] == "Bearer server-token"


def test_search_issues_uses_per_request_token(monkeypatch):
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)
    fake = patch_client(monkeypatch, FakeResponse(payload={"items": []}))
    asyncio.run(github.search_issues(scan_issue(), "owner/repo", token="ghp_searchtoken"))
    _, _, _, headers = fake.requests[-1]
    assert headers["Authorization"] == "Bearer ghp_searchtoken"


# A 1x1 transparent PNG as a data URI.
TINY_PNG = (
    "data:image/png;base64,"
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
)


def test_normalize_violations_carries_screenshot():
    from backend.app.services.scanner import normalize_violations

    violations = [
        {
            "id": "image-alt",
            "help": "Images must have alternative text",
            "impact": "critical",
            "tags": ["wcag111"],
            "nodes": [{"html": "<img>", "target": ["main img"]}],
            "screenshot": TINY_PNG,
        }
    ]
    issues = normalize_violations(violations)
    assert issues[0].screenshot == TINY_PNG


def test_markdown_body_embeds_screenshot_when_url_present():
    body = github.markdown_body(generated_issue(), screenshot_url="https://raw.example/img.png")
    assert "## Screenshot" in body
    assert "![Captured element from the live accessibility scan](https://raw.example/img.png)" in body


def test_markdown_body_omits_screenshot_section_when_absent():
    body = github.markdown_body(generated_issue())
    assert "## Screenshot" not in body


def test_upload_screenshot_returns_download_url(monkeypatch):
    fake = patch_client(
        monkeypatch,
        FakeResponse(status_code=201, payload={"content": {"download_url": "https://raw.example/x.png"}}),
    )
    url = asyncio.run(github._upload_screenshot("owner/repo", TINY_PNG, "ghp_token"))
    assert url == "https://raw.example/x.png"
    method, put_url, body, _ = fake.requests[-1]
    assert method == "PUT"
    assert "/contents/.a11y-screenshots/" in put_url
    assert "data:image" not in body["content"]  # data-URI prefix stripped before commit


def test_upload_screenshot_degrades_on_permission_error(monkeypatch):
    patch_client(monkeypatch, FakeResponse(status_code=403, payload={"message": "Resource not accessible"}))
    url = asyncio.run(github._upload_screenshot("owner/repo", TINY_PNG, "ghp_token"))
    assert url is None


def test_create_issue_embeds_uploaded_screenshot(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "server-token")
    # One response serves both the PUT (content.download_url) and POST (number/html_url).
    fake = patch_client(
        monkeypatch,
        FakeResponse(
            status_code=201,
            payload={
                "content": {"download_url": "https://raw.example/shot.png"},
                "number": 5,
                "html_url": "https://github.com/owner/repo/issues/5",
            },
        ),
    )
    result = asyncio.run(github.create_issue("owner/repo", generated_issue(), screenshot=TINY_PNG))
    assert result["number"] == 5
    # The final POST body must embed the uploaded screenshot URL.
    method, _, post_body, _ = fake.requests[-1]
    assert method == "POST"
    assert "https://raw.example/shot.png" in post_body["body"]


def test_create_issue_still_succeeds_when_screenshot_upload_fails(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "server-token")
    # PUT fails (403) but POST returns 201 — issue is created without the image.
    # FakeClient returns the same response for both, so make it a 201 that lacks
    # a download_url; _upload_screenshot then returns None.
    fake = patch_client(
        monkeypatch,
        FakeResponse(status_code=201, payload={"number": 9, "html_url": "https://github.com/owner/repo/issues/9"}),
    )
    result = asyncio.run(github.create_issue("owner/repo", generated_issue(), screenshot=TINY_PNG))
    assert result["number"] == 9
    method, _, post_body, _ = fake.requests[-1]
    assert "## Screenshot" not in post_body["body"]
