import asyncio

import pytest
from fastapi import HTTPException

from backend.app.models import GeneratedIssue, ScanIssue
from backend.app.services import github


class FakeResponse:
    def __init__(self, status_code=200, payload=None, headers=None):
        self.status_code = status_code
        self._payload = payload or {}
        self.headers = headers or {}

    def json(self):
        return self._payload


class FakeClient:
    def __init__(self, response):
        self.response = response
        self.requests = []

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False

    async def get(self, url, params=None, headers=None):
        self.requests.append(("GET", url, params, headers))
        return self.response

    async def post(self, url, json=None, headers=None):
        self.requests.append(("POST", url, json, headers))
        return self.response


def scan_issue() -> ScanIssue:
    return ScanIssue(
        id="button-name",
        title="Buttons must have discernible text",
        severity="High",
        wcag_criterion="4.1.2",
        wcag_url="https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html",
        element="<button></button>",
        selector="header button.search-icon",
        impact="Screen reader users cannot identify the search button.",
        description="The button has no accessible name.",
        occurrences=1,
        tags=["accessibility", "wcag-4.1.2", "buttons", "aria"],
    )


def generated_issue() -> GeneratedIssue:
    return GeneratedIssue(
        title="[A11y] Search button has no accessible name",
        description="The search button is missing an accessible name.",
        repro_steps=["Open the page.", "Focus the search button."],
        expected_result="The button is announced as Search.",
        actual_result="The button is announced without a name.",
        severity="High",
        labels=["accessibility", "bug"],
        acceptance_criteria=["The button has an accessible name.", "The axe rule passes."],
        environment="Chrome and NVDA",
        wcag_reference="https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html",
    )


def patch_client(monkeypatch, response):
    fake = FakeClient(response)
    monkeypatch.setattr(github.httpx, "AsyncClient", lambda timeout: fake)
    return fake


def test_search_issues_normalizes_and_scores_results(monkeypatch):
    patch_client(
        monkeypatch,
        FakeResponse(
            payload={
                "items": [
                    {
                        "number": 7,
                        "title": "Search button accessibility name missing",
                        "state": "open",
                        "labels": [{"name": "accessibility"}],
                        "assignee": {"login": "hardik"},
                        "created_at": "2026-06-01T12:00:00Z",
                        "body": "WCAG 4.1.2 button-name failure in header.",
                        "html_url": "https://github.com/owner/repo/issues/7",
                    }
                ]
            }
        ),
    )
    results, summary, source = asyncio.run(github.search_issues(scan_issue(), "owner/repo"))
    assert source == "github"
    assert "ranked by keyword similarity" in summary
    assert results[0].number == 7
    assert results[0].similarity_score > 5
    assert "WCAG" in results[0].similarity_explanation


def test_search_issues_translates_rate_limit_to_fallback(monkeypatch):
    patch_client(
        monkeypatch,
        FakeResponse(
            status_code=403,
            payload={"message": "API rate limit exceeded"},
            headers={"x-ratelimit-remaining": "0", "x-ratelimit-reset": "1800000000"},
        ),
    )
    results, summary, source = asyncio.run(github.search_issues(scan_issue(), "owner/repo"))
    assert results
    assert source == "fallback"
    assert "rate limit exceeded" in summary.lower()


def test_markdown_body_contains_required_sections():
    body = github.markdown_body(generated_issue())
    assert "## Description" in body
    assert "## Steps to reproduce" in body
    assert "- [ ] The button has an accessible name." in body
    assert "Generated by A11y GitHub Issue Logger" in body


def test_create_issue_requires_github_token(monkeypatch):
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)
    with pytest.raises(HTTPException) as exc:
        asyncio.run(github.create_issue("owner/repo", generated_issue()))
    assert exc.value.status_code == 503


def test_create_issue_translates_github_error(monkeypatch):
    monkeypatch.setenv("GITHUB_TOKEN", "token")
    patch_client(monkeypatch, FakeResponse(status_code=404, payload={"message": "Not Found"}))
    with pytest.raises(HTTPException) as exc:
        asyncio.run(github.create_issue("owner/repo", generated_issue()))
    assert exc.value.status_code == 404
    assert "repository was not found" in exc.value.detail
