import { useState } from "react";
import IssueEditor from "../components/IssueEditor";
import { CheckCircleIcon, CheckIcon, ExternalLinkIcon } from "../components/icons";
import { postJson } from "../services/api";
import { recordLoggedIssue } from "../services/history";

function buildMarkdown(issue) {
  const steps = issue.repro_steps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  const criteria = issue.acceptance_criteria.map((c) => `- [ ] ${c}`).join("\n");
  return `## Description
${issue.description}

## Steps to reproduce
${steps}

## Expected result
${issue.expected_result}

## Actual result
${issue.actual_result}

## Acceptance criteria
${criteria}

## Environment
${issue.environment}

## WCAG reference
${issue.wcag_reference}

**Severity:** ${issue.severity}

---
_Generated by A11y GitHub Issue Logger_`;
}

export default function ReviewPage({ state, setState, back, reset }) {
  const [repo, setRepo] = useState(state.repo || "");
  const [pat, setPat] = useState("");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  async function log() {
    setBusy(true);
    setError("");
    setState((v) => ({ ...v, repo }));
    try {
      const body = { repo, issue_data: state.generated };
      if (pat) body.github_token = pat;
      if (state.selected?.screenshot) body.screenshot = state.selected.screenshot;
      const logged = await postJson("/api/log-issue", body);
      setResult(logged);
      recordLoggedIssue({ url: state.url, number: logged.issue_number, htmlUrl: logged.html_url });
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function copyMarkdown() {
    try {
      await navigator.clipboard.writeText(buildMarkdown(state.generated));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard access denied — silent */
    }
  }

  if (result) {
    return (
      <section>
        <div className="success-card">
          <div className="success-icon" style={{ color: "var(--ok)" }}>
            <CheckCircleIcon />
          </div>
          <h2>Issue #{result.issue_number} created</h2>
          <p>The accessibility issue has been logged to <strong>{repo}</strong>.</p>
          <a href={result.html_url} target="_blank" rel="noreferrer">
            Open on GitHub <ExternalLinkIcon size={15} />
          </a>
        </div>
        <div className="actions" style={{ justifyContent: "center" }}>
          <button onClick={reset}>Start a new scan</button>
        </div>
      </section>
    );
  }

  return (
    <section>
      <p className="eyebrow">GitHub · Ready to Log</p>
      <h1>GitHub Issue — Ready to Log</h1>
      <p style={{ color: "var(--text-secondary)", marginTop: 8, marginBottom: 24, fontSize: ".92rem" }}>
        AI-generated from your A11y finding. Review every field, make any final edits, then log directly to GitHub.
      </p>

      <IssueEditor
        issue={state.generated}
        source={state.generationSource}
        onChange={(generated) => setState((v) => ({ ...v, generated }))}
      />

      <div className="repo-bar" style={{ marginTop: 20 }}>
        <label>
          Target repository
          <input
            type="text"
            placeholder="owner/repository"
            value={repo}
            onChange={(e) => setRepo(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && repo && !busy && log()}
            aria-label="GitHub repository in owner/name format"
          />
        </label>
        <label>
          GitHub PAT
          <input
            type="password"
            placeholder="ghp_… or github_pat_… (optional)"
            value={pat}
            onChange={(e) => setPat(e.target.value)}
            aria-label="GitHub personal access token — optional if server token is configured"
            autoComplete="off"
          />
        </label>
        <button onClick={copyMarkdown} aria-live="polite">
          {copied ? <><CheckIcon size={15} aria-hidden="true" />Copied</> : "Copy Markdown"}
        </button>
      </div>

      {state.selected?.screenshot && (
        <p className="muted" style={{ fontSize: ".78rem", marginTop: 12 }}>
          A captured element screenshot will be committed to <code>.a11y-screenshots/</code> in
          the target repo and embedded in the issue. Requires <code>Contents: write</code> on your
          token; if unavailable, the issue is still logged without the image.
        </p>
      )}

      {error && <p className="alert error" role="alert">{error}</p>}

      <div className="actions">
        <button className="ghost" onClick={back}>← Back</button>
        <button
          className="primary"
          disabled={busy || !repo}
          onClick={log}
        >
          {busy ? (
            <>
              <span className="spinner" style={{ width: 16, height: 16, borderWidth: 2 }} aria-hidden="true" />
              Logging…
            </>
          ) : "Log issue to GitHub"}
        </button>
      </div>
    </section>
  );
}
